<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.7 setup script
 * Date: Fri, 11 Dec 2020 12:12:18 +0000
 */

$cfg['Servers'] = array (
);
$cfg['blowfish_secret'] = '.nA<kA|&AQnv{1^EF$#(jt(fFG8[&)+';
$cfg['DefaultLang'] = 'es';
$cfg['DefaultTransformations']['Substring'] = array (
  0 => '0',
  1 => 'all',
  2 => '…',
);
$cfg['DefaultTransformations']['External'] = array (
  0 => '0',
  1 => '-f /dev/null -i -wrap -q',
  2 => '1',
  3 => '1',
);
$cfg['DefaultTransformations']['PreApPend'] = array (
);
$cfg['DefaultTransformations']['DateFormat'] = array (
  0 => '0',
  1 => 'local',
);
$cfg['DefaultTransformations']['Inline'] = array (
  0 => '100',
  1 => '100',
);
$cfg['DefaultTransformations']['TextImageLink'] = array (
  0 => '100',
  1 => '50',
);
$cfg['DefaultTransformations']['TextLink'] = array (
);
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>